---
- name: Install python mysqldb package
  ansible.builtin.apt:
    pkg: "{{ etherpad_python_mysql_package }}"
    state: present

- name: Create mysql database
  community.mysql.mysql_db:
    name: "{{ etherpad_mysql_database_name }}"
    collation: "{{ etherpad_mysql_database_collation }}"
    login_host: "{{ etherpad_mysql_database_host }}"
    login_port: "{{ etherpad_mysql_database_port }}"
    login_user: "{{ etherpad_mysql_database_user }}"
    login_password: "{{ etherpad_mysql_database_password }}"
    state: present
  register: database

- name: Copy mysqldb schema # noqa no-handler
  ansible.builtin.template:
    src: schema.sql.j2
    dest: /tmp/etherpad_schema.sql
    mode: 0755
  when: database is changed

- name: Import mysqldb schema # noqa no-handler
  community.mysql.mysql_db:
    name: "{{ etherpad_mysql_database_name }}"
    collation: "{{ etherpad_mysql_database_collation }}"
    login_host: "{{ etherpad_mysql_database_host }}"
    login_port: "{{ etherpad_mysql_database_port }}"
    login_user: "{{ etherpad_mysql_database_user }}"
    login_password: "{{ etherpad_mysql_database_password }}"
    state: import
    target: /tmp/etherpad_schema.sql
  when: database is changed

- name: Remove mysqldb schema file # noqa no-handler
  ansible.builtin.file:
    path: /tmp/etherpad_schema.sql
    state: absent
  when: database is changed

- name: Fail if mysql user has no password
  ansible.builtin.fail:
    msg: "You need to set a password for mysql user!"
  when: etherpad_mysql_database_password is undefined or etherpad_mysql_database_password | length == 0

- name: Register systemd version number
  ansible.builtin.shell: |
    set -o pipefail
    systemd --version | head -1 | cut -d' ' -f2
  args:
    executable: /bin/bash
  check_mode: no
  changed_when: false
  register: systemd_version
  when: etherpad_mysql_systemd_dropin_enabled

- name: Create directory for etherpads systemd drop-in
  ansible.builtin.file:
    path: /etc/systemd/system/etherpad-lite.service.d/
    state: directory
    owner: root
    group: root
    mode: "0750"
  when: etherpad_mysql_systemd_dropin_enabled

- name: Create systemd drop-in for etherpad
  ansible.builtin.template:
    src: etc/systemd/system/etherpad-lite.service.d/10-start-limit.conf.j2
    dest: /etc/systemd/system/etherpad-lite.service.d/10-start-limit.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd
  when: etherpad_mysql_systemd_dropin_enabled
