---
- name: Allow overcommiting of memory
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/90-ansible-vm.conf
    sysctl_set: yes

- name: Ensure redis module for nodejs is present
  community.general.npm:
    name: redis
    path: "{{ etherpad_path }}"
    state: present
  become: true
  become_user: "{{ etherpad_user }}"
  when: "etherpad_db_type == 'redis'"
