---
- name: Restart etherpad-lite
  service:
    name: etherpad-lite
    state: restarted

- name: Ensure etherpad dependencies are latest  # noqa no-changed-when
  command:
    cmd: bin/installDeps.sh
    chdir: "{{ etherpad_path }}"
  become: true
  become_user: "{{ etherpad_user }}"
  notify: Fix package-lock.json # this is a hack

- name: Fix package-lock.json # noqa command-instead-of-module no-changed-when
  command:
    cmd: git checkout src/package-lock.json
    chdir: "{{ etherpad_path }}"
  become: true
  become_user: "{{ etherpad_user }}"
  notify: Restart etherpad-lite

- name: Reload systemd
  systemd:
    daemon_reload: true
  become: true
