---
- name: Converge
  hosts: all
  become: yes
  roles:
    - role: ansible-role-etherpad
  vars:
    etherpad_repository_version: 2.0.3
    etherpad_api_key: "secure_api_key"
    etherpad_abiword_enabled: true
